// Generated by docs/tutoriais/build.py from the exported PDFs.
export const TUTORIAL_GROUPS = [
  {
    'id': 'consulta',
    'documents': [
      {
        'id': 'consulta-download',
        'version': '1.0',
        'date': '06/10/2026',
        'pages': 8,
        'size': '315 KB',
      },
    ],
  },
  {
    'id': 'servidores',
    'documents': [
      {
        'id': 'acesso',
        'version': '1.0',
        'date': '06/10/2026',
        'pages': 7,
        'size': '363 KB',
      },
      {
        'id': 'submissao',
        'version': '1.0',
        'date': '06/10/2026',
        'pages': 12,
        'size': '498 KB',
      },
    ],
  },
  {
    'id': 'nugecid',
    'documents': [
      {
        'id': 'revisao-publicacao',
        'version': '1.0',
        'date': '06/10/2026',
        'pages': 8,
        'size': '279 KB',
      },
      {
        'id': 'fluxo-deposito',
        'version': '1.0',
        'date': '06/10/2026',
        'pages': 5,
        'size': '161 KB',
      },
    ],
  },
];
